package Web.Entity.Pojo.Portfolio;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MenuCategory generated by hbm2java
 */
@Entity
@Table(name = "menuCategory", schema = "dbo", catalog = "portfolio")
public class MenuCategory implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String imagen;
	private Date date;

	public MenuCategory() {
	}

	public MenuCategory(int id, String name, String description, String imagen, Date date) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.imagen = imagen;
		this.date = date;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "imagen", nullable = false)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 23)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
