package Web.Entity.Pojo.Portfolio;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NavegadorFoto generated by hbm2java
 */
@Entity
@Table(name = "NavegadorFoto", schema = "dbo", catalog = "portfolio")
public class NavegadorFoto implements java.io.Serializable {

	private int id;
	private String srcImage;
	private String srcImagenMiniatura;
	private String descripcion;
	private String titulo;

	public NavegadorFoto() {
	}

	public NavegadorFoto(int id, String srcImage, String srcImagenMiniatura, String descripcion, String titulo) {
		this.id = id;
		this.srcImage = srcImage;
		this.srcImagenMiniatura = srcImagenMiniatura;
		this.descripcion = descripcion;
		this.titulo = titulo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "srcImage", nullable = false)
	public String getSrcImage() {
		return this.srcImage;
	}

	public void setSrcImage(String srcImage) {
		this.srcImage = srcImage;
	}

	@Column(name = "srcImagenMiniatura", nullable = false)
	public String getSrcImagenMiniatura() {
		return this.srcImagenMiniatura;
	}

	public void setSrcImagenMiniatura(String srcImagenMiniatura) {
		this.srcImagenMiniatura = srcImagenMiniatura;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

}
