package Persistence.MapperXML.Proyecto;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", schema = "dbo", catalog = "portfolio")
public class Proyecto implements java.io.Serializable {

	private int id;
	private String nombre;
	private String descripcion;
	private String categoria;
	private String imagenSrc;
	private Date fechaActualizacion;

	public Proyecto() {
	}

	public Proyecto(int id, String nombre, String descripcion, String categoria, String imagenSrc,
			Date fechaActualizacion) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.categoria = categoria;
		this.imagenSrc = imagenSrc;
		this.fechaActualizacion = fechaActualizacion;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "categoria", nullable = false)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "imagenSrc", nullable = false)
	public String getImagenSrc() {
		return this.imagenSrc;
	}

	public void setImagenSrc(String imagenSrc) {
		this.imagenSrc = imagenSrc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaActualizacion", nullable = false, length = 23)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Override
	public String toString() {
		return "Proyecto [id=" + id + ", nombre=" + nombre + ", descripcion=" + descripcion + ", categoria=" + categoria
				+ ", imagenSrc=" + imagenSrc + ", fechaActualizacion=" + fechaActualizacion + "]";
	}
	
	

}
